services:
  php-apache:
    build: .
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - minha-rede
  mysql:
  
    image: mysql:8.4.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario_livros
      MYSQL_PASSWORD: senha_livros
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: